#!/bin/bash
# Config variables.
COLLECTION_FILE="$1"
REPORT_TITLE="Integration Report"

# Newman report html command.
./node ./node_modules/newman/bin/newman.js run "$COLLECTION_FILE" -r htmlextra --reporter-htmlextra-title "$REPORT_TITLE" --reporter-htmlextra-titleSize 4 --reporter-htmlextra-export ./report-html/report.html

# Call default browser.
x-www-browser "file://`pwd`/report-html/report.html"
